name: Auto Label PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title for labels
        id: label-check
        run: |
          pr_title="${{ github.event.pull_request.title }}"
          if [[ $pr_title == *"docs"* ]]; then
            echo "ğŸ“š docs"
          elif [[ $pr_title == *"feat"* ]]; then
            echo "â˜ï¸ feature"
          elif [[ $pr_title == *"fix"* ]]; then
            echo "ğŸ”¨ fix"
          elif [[ $pr_title == *"refactor"* ]]; then
            echo "ğŸ›  refactor"
          elif [[ $pr_title == *"setup"* ]]; then
            echo "ğŸ§¹ setup"
          elif [[ $pr_title == *"style"* ]]; then
            echo "ğŸ–Œ style"
          elif [[ $pr_title == *"test"* ]]; then
            echo "ğŸ§ª test"
          fi
        env:
          PR_LABEL: ${{ steps.label-check.outputs }}

      - name: Add Label to PR
        if: ${{ env.PR_LABEL }} != ''
        run: |
          label_name="${{ env.PR_LABEL }}"
          gh pr edit ${{ github.event.pull_request.number }} --add-label "$label_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
