name: Discord PR Notification

on:
  pull_request:
    types: [opened]

jobs:
  pr-notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        id: notify
        run: |
          echo "json: ${{ github.event.pull_request | toJSON }}"
          echo "${{ github.event.pull_request.draft }}"
          echo "${{ github.event.pull_request.state }}"
          echo "base: ${{ github.event.pull_request.base.ref | split("/") | first }}"
          echo "head: ${{ github.event.pull_request.head.ref | split("/") | first }}"
          JSON_DATA='{
            "content": "ğŸ“£ ${{ github.event.pull_request.user.login }} ë‹˜ì´ ìƒˆë¡œìš´ PRë¥¼ ìƒì„±í–ˆìŠµë‹ˆë‹¤.",
            "embeds": [
              {
                "title": "${{ github.event.pull_request.title }}",
                "description": "" ,
                "color": 3368703,
                "url": ${{ github.event.pull_request.html_url }}"
              }
            ]
          }'
          curl -X POST \
            -H 'Content-Type: application/json' \
            -d "$JSON_DATA" \
            ${{ secrets.DISCORD }}
