name: Discord PR Notification

on:
  pull_request:
    types: [opened, reopened]

jobs:
  pr-notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        id: notify
        # if: ${{ github.event.pull_request.open == 'true' }}
        run: |
          echo "${{ github.event.pull_request.draft }}"
          echo "${{ github.event.pull_request.state }}"
          JSON_DATA='{
            "content": "✔️ ${{ github.event.pull_request.user.login }} 님이 ${{ github.event.pull_request.number }}번 PR를 Open했습니다.",
            "embeds": [
              {
                "title": "${{ github.event.pull_request.title }}",
                "description": "Branch : ${{ github.event.pull_request.head.ref }} ➡️ ${{ github.event.pull_request.base.ref }} \nURL : ${{ github.event.pull_request.html_url }}" ,
                "color": 3368703,
              }
            ]
          }'
          curl -X POST \
            -H 'Content-Type: application/json' \
            -d "$JSON_DATA" \
            ${{ secrets.DISCORD }}
