name: Discord PR Notification

on:
  pull_request:
    types: [opened, reopened]

jobs:
  pr-notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        id: notify
        # if: ${{ github.event.pull_request.open == 'true' }}
        run: |
          echo "${{ github.event.pull_request.draft }}"
          echo "${{ github.event.pull_request.state }}"
          JSON_DATA='{
            "content": "ğŸ“£ ${{ github.event.pull_request.user.login }} ë‹˜ì´ #${{ github.event.pull_request.number }}ë²ˆ PRë¥¼ Opení–ˆìŠµë‹ˆë‹¤.",
            "embeds": [
              {
                "title": "${{ github.event.pull_request.title }}",
                "description": "${{ github.event.pull_request.base.ref }} <- ${{ github.event.pull_request.head.ref }}" ,
                "color": 3368703,
                "url": "${{ github.event.pull_request.html_url }}"
              }
            ]
          }'
          curl -X POST \
            -H 'Content-Type: application/json' \
            -d "$JSON_DATA" \
            ${{ secrets.DISCORD }}
