name: Discord PR Notification

on:
  pull_request:
    types: [opened, reopened]

jobs:
  pr-notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        id: notify
        run: |
          echo "test: ${{ github.event.pull_request }}"
          JSON_DATA='{
            "content": "ğŸ“£ ${{ github.event.pull_request.user.login }} ë‹˜ì´ ìƒˆë¡œìš´ PRë¥¼ ìƒì„±í–ˆìŠµë‹ˆë‹¤.",
            "embeds": [
              {
                "title": "#${{ github.event.pull_request.number }}ë²ˆ PR Title: ${{ github.event.pull_request.title }}",
                "description": "ë§ì€ ê´€ì‹¬ ë¶€íƒ ë“œë¦½ë‹ˆë‹¤." ,
                "color": 3368703,
                "url": ${{ github.event.pull_request.html_url }}"
              }
            ]
          }'
          curl -X POST \
            -H 'Content-Type: application/json' \
            -d "$JSON_DATA" \
            ${{ secrets.DISCORD }}
